name: HugoIsaacs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9384686171542853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090913'
    - '#37e3f5'
    - '#802a0a'
    - '#d4990c'
  brandStrength: 0.5
  lightness: 0.21487401449121535
  saturation: 0.1875
  rhythmicContrast: 0.5430930526927114
purpose: []
